### ISSUE TITLE
Object mapping relationships do not work with polymorphic types [DATAGRAPH-1341]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-neo4j#1904]
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1341](https://jira.spring.io/browse/DATAGRAPH-1341?redirect=false)** and commented

Hi everyone ! I'm using the version 1.1.1 of Spring Data Neo4j RX and I have a problem while defining a relationship property within a class hierarchy. In my use case, I have an abstract base class and several concrete implementations which extend it. Moreover, the base class has a property annotated with `@Relationship`, let's say with type REF: this kind of relationship is defined in the base class cause every concrete implementation actually has a type REF relationship, thus the relationship is a common property.

The `@node` annotation is not inherited from super-types and interfaces. You can, however, annotate your domain classes individually at every inheritance level. This allows polymorphic queries: You can pass in a base or intermediate classes and retrieve the correct, concrete instance for your nodes. This is only supported for abstract bases annotated with `@node`. The labels defined on such a class will be used as additional labels together with the labels of the concrete implementations.

Based on the above excerpt from the documentation and given the following object mapping:

```java
@Node("A") public abstract class A {
    @Id @GeneratedValue public Long id;
    public String name ;
    
    @Relationship(type="REF) public X reference ;
    
    @Node("B") public static class B extends A {           // a concrete implementation B
        // ... specific B properties here
    }
    // ... other concrete implementations here
}

@Node("X") public abstract class X {                       // end node of the relationship REF
    @Id @GeneratedValue public Long id;

     // ... other specific X properties here
}
```

Using a repository class defined for node type A, what I expect here is that a call to findAll (or findById) returns the concrete implementation of A with the reference property actually populated with an instance of the X object. Instead, what I get is a null value for the reference property. Furthermore, reading the log, I was able to verify that the generated query is correct and that it actually retrieves the related X object: executing the same query within the neo4j browser also work as expected.

Is there a bug while mapping the query response to the actual object mapping, or have I missed something and my object mapping is not well defined?

Note: the above code is simplified for brevity but my real implementation makes use of Lombok, thus every property is actually private and accessed using the Lombok defined getter and setter

---

**Affects:** 6.0 M2 (2020.0.0)

**Reference URL:** https://github.com/neo4j/sdn-rx/issues/269

**Comment by meistermeier** [comment]
This was already solved

**Comment by calltherain** [comment]
Hi @meistermeier 

I can still reproduce this issue using 6.3.2 and 6.3.10. Haven't test v7 though. 
The SDN auto generated Cypher is similar like this (simplified):

```
MATCH (a:A) WHERE a.id = $id 
RETURN a { .*, 
  __internalNeo4jId__: id(a), 
  __nodeLabels__: labels(a), 
  A_REF_X: [ (a)-[:REF]->(x:X) | x { .*
      __internalNeo4jId__: id(x), 
      __nodeLabels__: labels(x) 
  }]
}  
```
And SDN can't populate A.reference field value, it's a null.

But If I override the repository method with custom query, and rename `A_REF_X` to `B_REF_X` then it works.
