### ISSUE TITLE
Support for play framework or others

### ISSUE THREAD

**Issue by yakisama12** [spring-projects/spring-data-neo4j#315]
Neo4jMappingContext ctor throws class not found exception while using play framework, Java class loader cannot find classes in play framework packages, since play framework uses its own class loader and not the default Java class loader.

Perhaps an overload ctor with a class loader as a parameter is a good solution.

Similar issue was resolved in neo4j-ogm, reference -
https://github.com/neo4j/neo4j-ogm/issues/34

Thanks, Nati

**Comment by luanne** [comment]
Which version of SDN are you using?

**Comment by yakisama12** [comment]
Sorry forgot to mention it, I am migrating from 3.4.0 to SDN 4

**Comment by luanne** [comment]
This should work if you're using 4.0.0.RELEASE
It was fixed in the neo4j-ogm 1.1.2

**Comment by yakisama12** [comment]
My senario is as follows- 
I'm using spring data neo4j as a plugin, on start I initialize SpringApplication with a class that extends Neo4jConfiguration, in my class I override the neo4jserver method to set the server address, user and password, also override the getSessionFactory returning new SessionFactory with my domain(model) package.

Starting the spring application triggers autowire of beans located in Neo4jConfiguration such as Neo4jMappingContext which lead to the exception above.
The metadata object that is passed on to the ctor contains my classes and I can see them, but when trying to load them it fails, probably because its not using play class loader

**Comment by unterstein** [comment]
Hi,
i have the same issue using play (2.4 or 2.5) and SDN (4.0 or 4.1).

@luanne this issue is unfortunately not fixed in 4.0.0.RELEASE :-(

The problem is, like @yakisama12 said, that the classes are not found by the classloader existing in Neo4JMappingContext. Therefore i added an extra constructor to Neo4jMappingContext to accept an external classloader, see https://github.com/unterstein/spring-data-neo4j/commit/b8c8e5fccabca185e4424670edd767c90d8173ac


Then it is possible to do something like this in the neo4j configuration:

```
@Configuration
@EnableNeo4jRepositories(basePackages = Array("neo4j.repositories"))
@EnableTransactionManagement
class SpringNeo4jConfiguration extends Neo4jConfiguration {

  @Bean
  override def neo4jMappingContext: Neo4jMappingContext = {
    new Neo4jMappingContext(getSessionFactory.metaData, this.getClass.getClassLoader)
  }

  @Bean
  override def getSessionFactory: SessionFactory = new SessionFactory("neo4j.models")
}
```

This solves with the ClassNotFoundExceptions.

Cheers
Johannes

**Comment by tuxBurner** [comment]
+1

**Comment by vince-bickers** [comment]
Hi 

We don't want to introduce another API change if we can help it. The OGM classloader mechanism supports Play and other containers/frameworks. But it appears that Neo4jMappingContext in SDN 4 is not using the OGM classloader mechanism, hence the problem. The OGM classloader is available to the Neo4jMappingContext, so the fix should be simple. We'll try to get this resolved ASAP.

**Comment by unterstein** [comment]
Hi @vince-bickers,

my commit do not break the current api, I added just an alternative constructor. But if you can handle this issue during usage of OGM classloading this would be also really fine. Is this possible to ship during SDN 4.1? *lovely smile* 

Cheers
Johannes

**Comment by vince-bickers** [comment]
I expect we'll have a fix available in the next few hours :)

**Comment by vince-bickers** [comment]
Tracked here: https://jira.spring.io/browse/DATAGRAPH-830

**Comment by vince-bickers** [comment]
A fix is now available in the latest snapshot release:

4.1.0.BUILD-SNAPSHOT

Please confirm whether this issue is now fixed.

**Comment by unterstein** [comment]
Thanks Vince, this enables starting of SDN in play ! :-)

Currently there are an issue according class reloading, like i wrote in jira. Hope we can also solve this issue :)

**Comment by unterstein** [comment]
Hi,

through https://jira.spring.io/browse/DATAGRAPH-830, this ticket is resolved in my opinion. I provided a working sample of play 2.5 (RC) and SDN 4.1 (SNAPSHOT) here https://github.com/unterstein/play-2.5-sdn-4.1.

Initially loading of classes works, as well as loading of classes after a play reload works as expected :)

Thanks a lot @vince-bickers !
